# -*- coding: utf-8 -*-
"""logistics_app.ipnyb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMwstYeHjKXuQAu-HNHG8XE30oHV4ewP
"""

import streamlit as st
import pandas as pd

# ==========================================
# 1. KONFIGURASI HALAMAN DASHBOARD
# ==========================================
st.set_page_config(page_title="Logistics & Carrier Performance", page_icon="📦", layout="wide")

st.title("📦 Logistics & Carrier Performance Dashboard")
st.markdown("**Data Operations & Operational Analytics — Portfolio Project**")
st.write("---")

# ==========================================
# 2. FUNGSI LOAD DATA (MEMBACA 3 CSV)
# ==========================================
@st.cache_data
def load_data():
    # Nama file ini harus SAMA PERSIS dengan hasil unduhan dari Colab
    df_cust = pd.read_csv('customer.xlsx - customer.csv')
    df_perf = pd.read_csv('customer.xlsx - logistics_performance.csv')
    df_ship = pd.read_csv('customer.xlsx - shipment.csv')
    return df_cust, df_perf, df_ship

try:
    df_cust, df_perf, df_ship = load_data()

    # ==========================================
    # 3. KARTU METRIK RINGKASAN DI BAGIAN ATAS
    # ==========================================
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric(label="👥 Total Registrasi Customer", value=f"{len(df_cust)} Users")
    with col2:
        st.metric(label="🚢 Total Shipment Logs", value=f"{len(df_ship)} Pengiriman")
    with col3:
        st.metric(label="📊 Carrier Performance Records", value=f"{len(df_perf)} Entri")

    st.write("---")

    # ==========================================
    # 4. TAB NAVIGASI UNTUK MASING-MASING TABEL
    # ==========================================
    st.markdown("### 🗂️ Eksplorasi Data Base Logistik")
    tab1, tab2, tab3 = st.tabs(["👥 Profil Customer", "📊 Kinerja Carrier (Vendor)", "🚢 Manifes Pengiriman"])

    with tab1:
        st.subheader("Data Demografi & Profil Pelanggan")
        st.dataframe(df_cust, use_container_width=True)

    with tab2:
        st.subheader("Analisis Performa Waktu & Kerusakan Vendor Ekspedisi")
        st.dataframe(df_perf, use_container_width=True)

    with tab3:
        st.subheader("Detail Logistik Barang Lintas Wilayah")
        st.dataframe(df_ship, use_container_width=True)

except FileNotFoundError:
    st.error("❌ Eror: File CSV tidak ditemukan. Pastikan 3 file CSV (customer, performance, shipment) sudah berada di folder yang sama dengan script ini!")

st.write("---")
st.caption("Logistics Dashboard System | Developed by Ahmad Gozali Abbas")